services:
  election-forecast-collector:
    build: ..
    environment:
      EFC_CONTACT_EMAIL: "replace-me@example.com"
    volumes:
      - ./data:/data
    command: ["collect", "--output-dir", "/data", "--save-raw"]
